name: Firebase Deploy

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Web App
        run: npm run build

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RUNNING_SAGA_D07A9 }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          npx firebase-tools deploy --only hosting --project running-saga-d07a9 --non-interactive

